services:
  ros2_piperx:
    build: .
    container_name: ros2_piperx

    network_mode: host
    ipc: host
    privileged: true

    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_LOCALHOST_ONLY=0
      - FASTDDS_BUILTIN_TRANSPORTS=UDPv4
      - QT_X11_NO_MITSHM=1

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/piperx_ws:/workspace/piperx_ws
      - ${HOME}/pyAgxArm:/workspace/pyAgxArm
      - /dev:/dev
      - /run/udev:/run/udev:ro

    stdin_open: true
    tty: true
